input: 
	node --max_old_space_size=16384 solution_part1.js < input.txt

inputDebug: 
	node-debug solution_part1.js < input.txt

example:
	node solution_part1.js < exampleInput.txt

exampleDebug:
	node-debug solution_part1.js < exampleInput.txt
